### PR TITLE
bump to 6.4.0

### PR DESCRIPTION
**Pull request by gingerlime**

### CODE REVIEW

**Comment by konradreiche** [comment]
@eduherraiz Would be great to get this in as soon as possible as it it fixing a production critical bug for us. Thank you :bowing_man:

**Comment by michelazzo** [comment]
I was going just after that Thumbor upgrade. Could you please merge it?

**Comment by canuc** [comment]
Plz merge!

**Comment by shaneog** [comment]
Version 6.4.2 is [released](https://github.com/thumbor/thumbor/releases/tag/6.4.2).

**Comment by gingerlime** [comment]
I'd be happy to update the PR to 6.4.2, but it looks like this project is dead :( (latest commit was almost a year ago...)

**Comment by shaneog** [comment]
@eduherraiz Can you confirm if this project is dead/deprecated/unloved?

**Comment by eduherraiz** [comment]
Hello guys,

The upgrade to 6.4 is not quite easy like this PR pretends to be.
We will have to check version dependencies and new configurations variables for get a new release for this thumbor's version. I have planned the new version changing the building process, python version (2 -> 3) and trying to get a smaller image with some improvements using new multi-stage docker build. 
I reallly apreciate your comments but I can't deal with this big effort now. 
At least not on my own time, if you really need this changes on production system we can talk about to do it in a professional way.
I'm sure I will do this changes but I can't say when. 
(I tried a fast patch in branch 6.4.2 for your testing but the docker push system is broken on Travis CI)

**Comment by gingerlime** [comment]
@eduherraiz thanks. I'd be happy to help with a more thorough upgrade if you provide more details of what you have in mind (I already suggested it on #79).

Until then, this (like your 6.4.2 branch) is just a patch, but it should work fine, and allow us to use the latest thumbor with docker containers hopefully. 

Not sure what you mean about the Travis push, because it looks green. Would be great to have the latest thumbor version available on docker hub.

**Comment by eduherraiz** [comment]
Ok. I will share my thoughts for the new version.
The build is green but the docker push fails for a auth problem. I will check this today!

**Comment by eerootsus** [comment]
I have actually managed to update to 6.4.2 and am running this in production.
https://github.com/eerootsus/docker-thumbor

Image available at whitewizardee/thumbor

**Comment by gingerlime** [comment]
@eerootsus thanks. Forking is always a possibility, but ideally we focus efforts on one project / main docker image, rather than create yet another project/image out there.

I hope this project can continue to be this main one, because it's really addressing more than just the basics for hosting thumbor. To remain the central point, then I think it needs a bit more love. PRs should be more timely considered and the whole project needs to move forward in step with core thumbor. I think that several people are happy to contribute, but those contributions still need to be accepted and managed by @eduherraiz.

**Comment by shaneog** [comment]
@eduherraiz Thanks for responding. I'd also be happy to help.

~~There are some other upgrades I would like, particularly upgrading `tc-aws` to [6.02](https://github.com/thumbor-community/aws/releases/tag/6.0.2) so I can use Google Cloud Storage.~~

~~Would you accept some small PRs for minor things like that?~ EDIT: my fork was outdated 🤦‍♂️ 

Also, it would be fantastic if you could, for example, open an issue with a list of the things you would like done for the next release so that contributors can target those areas specifically, along with linking PRs to the issue.

**Comment by shaneog** [comment]
@eduherraiz https://github.com/APSL/docker-thumbor/pull/91 should fix the Travis docker push issue.

**Comment by eduherraiz** [comment]
Thank you @shaneog!! Building in 6.4.2
I hope could you check this new version and solve by the moment your prod env.
IMHO The @eerootsus fork is not a good review of new thumbor's version needs. But thank you!
For the moment I'm closing this PR and open a new issue where share and discuss the new version plan.
It should be divided in subtasks and I hope we can share the load.

**Pull request closed without merging**
