### PR TITLE
6.4.2

### PR DESCRIPTION
**Pull request by eerootsus**
- Thumbor 6.4.2
- Botocore 1.9.7

### CODE REVIEW

**Comment by gingerlime** [comment]
Not sure why travis is red, but would love to get this merged.

**Comment by eerootsus** [comment]
RemoteCV image fails - seems to want to install really old botocore. I didn't have any need to change or update other images, just upgraded Thumbor.

**Comment by gingerlime** [comment]
@eduherraiz any chance to get this merged any time soon?

**Comment by gingerlime** [comment]
please also see #94 which includes this change, and more :)

**Pull request closed without merging**
